// keep all LE related constants
public without sharing class ConstantsforLE {
    //LEConstants.LEAccountCreationFail 
    
    public static final String LELeadCreationSuccess = 'Lead created successfully';
    public static final String LEAccountCreationSuccess = 'Account created successfully';
    public static final String LEAccountNotContactCreationSuccess  = 'Account created successfully, but influencer Contact couldnot be created';
     public static final String LEAccountContactCreationSuccess  = 'Account & Contact created successfully';
    
    public static final String LEAccountCreationFail = 'Account creation fails';
    public static final String LELeadCreationFail = 'Lead creation fails';
    public static final String LEContactFail = 'Contact creation fails';
    public static final String LECompanyInformationMissingforLeadCreation  = 'Error: The selected company has insufficient data to create a Lead. Company information is missing';
    public static final String LEContactInformationMissingforLeadCreation = 'Error: The selected company has insufficient data to create a Lead. Contact information is missing';
    public static final String LECompanyInformationMissingforAccountCreation  = 'Error: The selected company has insufficient data to create an influencer Account, Company information is missing';
    public static final String LEContactInformationMissingforAccountCreation = 'Contact information is missing';
    public static final String LEType = 'Lodging Econometrics'; // LEConstants.LEType
    public static final String LECreateLEAccount = 'createLEAccount';
    public static final String LECreateLELead = 'createLEAccount';
    public static final String LECreateLEContact = 'createLEContact';
    public static final String LERoleManagement = 'Management';
    public static final String LERoleDeveloperOwner = 'Developer/Owner';
}