/*** 
 @Author :     Haritha
 @Name   :     DummyApexClassForProcessBuilder
 @Created Date: 03/04/2018
 @Description: This class is used for Switch On/Off functionality for Process Builder.
 @Version:0.2
***/

public without sharing class DummyApexClassForProcessBuilder {
   /**
   *  @name: dummyMethodForProcessBuilder
   *  @param: Null
   *  @return: Null
   */
  @InvocableMethod
    public static void dummyMethodForProcessBuilder(){
        try{ } catch(exception ex){ex.getMessage();}
    }
}